import sqlite3
import requests

def test_db():
    conn = sqlite3.connect('backend/data/map_data.db')
    cursor = conn.cursor()
    q = "SELECT COUNT(*) FROM auctions WHERE (special_notes IS NULL OR special_notes = '' OR special_notes = '0' OR special_notes = '0.0' OR special_notes LIKE '0 %' OR special_notes LIKE '%대항력 없음%' OR special_notes LIKE '%대항력없음%')"
    cursor.execute(q)
    print('Count from DB:', cursor.fetchone()[0])
    
    # Also fetch the exact query generated by app.py by sending a request
    url = 'http://localhost:8000/api/map/auctions?special_rights=대항력없음'
    res = requests.get(url)
    print('API status:', res.status_code)
    print('API count:', len(res.json().get('data', [])))

if __name__ == '__main__':
    test_db()
